spring:
  datasource:
      name: druidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      sql-script-encoding: utf-8
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/openapi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: 123456
      druid:
        # ??????????????????????????????????????
        # ??????????????????????
        initial-size: 5
        # ??С?????????
        min-idle: 5
        # ????????????
        max-active: 50
        # ????????????????????
        max-wait: 30000
        # ???ü????ò??????μ??????????????????????λ?????
        time-between-eviction-runs-millis: 60000
        # ??????????????????С??????????λ?????
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        # ?????????true???????????????????????????????????????????????????timeBetweenEvictionRunsMillis?????validationQuery????????????Ч??
        test-while-idle: true
        # ????????????validationQuery????????????Ч?????????????????????
        test-on-borrow: false
        # ?黹????????validationQuery????????????Ч????????????????????
        test-on-return: false
        # ??PSCache??????????????????PSCache???С
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 50
        # 'wall'?????sql???
        #filters: wall
    #缓存redis
  cache:
    type: redis
  redis:
    host: 47.101.57.147
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 3
    password: 123456
    port: 6379
server:
  port: 8082
  tomcat:
      max-http-header-size: 8192
